# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xv54A9bIz53Qf3x1-uOA1DfkY3OD-8m-

Import and Load Dataset
"""

import pandas as pd
import numpy as np
from pathlib import Path

DATA_PATH = Path("/content/Hospital ER_Data.csv")
OUTPUTS = Path("../outputs")
OUTPUTS.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(DATA_PATH)
print(df.shape)
df.head()

"""Drop Irrelevant Identifiers"""

cols_to_drop = ["Patient Id", "Patient First Inital", "Patient Last Name"]
df = df.drop(columns=cols_to_drop, errors="ignore")

"""Parse Date & Add Time Features"""

df["Patient Admission Date"] = pd.to_datetime(
    df["Patient Admission Date"], errors="coerce", dayfirst=True
)
df["Admission_Year"] = df["Patient Admission Date"].dt.year
df["Admission_Month"] = df["Patient Admission Date"].dt.month
df["Admission_Day"] = df["Patient Admission Date"].dt.day
df["Admission_Hour"] = df["Patient Admission Date"].dt.hour
df["Admission_Weekday"] = df["Patient Admission Date"].dt.day_name()

"""Handle Missing Values"""

# Leave Satisfaction NA as-is
df["Patient Satisfaction Score"] = df["Patient Satisfaction Score"].fillna(
    df["Patient Satisfaction Score"].median()
)

# Boolean to int
df["Patient Admission Flag"] = df["Patient Admission Flag"].astype(int)

"""Save Clean Dataset"""

clean_path = Path("/content/er_clean.csv")
df.to_csv(clean_path, index=False)
print("Clean dataset saved to:", clean_path)